### ISSUE TITLE
sigmoid function miscalculation on the hidden layers' sum?

### ISSUE THREAD

**Issue by kostasx** [stevenmiller888/stevenmiller888.github.com#1]
When the sigmoid function (based on your [sigmoid node module](https://www.npmjs.com/package/sigmoid)) is applied to the hidden layer sums, I get the following results that differ from the ones mentioned on [your page](http://stevenmiller888.github.io/mind-how-to-build-a-neural-network/):

S(1.0) = 0.73105857863
S(1.3) = 0.78583498304
S(0.8) = 0.68997448112

am I missing something here?

**Comment by stevenmiller888** [comment]
Whoa you're right. That must've been confusing, really sorry about that!

**Comment by stevenmiller888** [comment]
Fixed! Thanks for the heads up dude

**Comment by stevenmiller888** [comment]
Fixing now

**Comment by kostasx** [comment]
Cool! Really interesting series of posts, by the way.

**Comment by stevenmiller888** [comment]
Nice dude, i'm glad you like them! Thanks for the heads up on the numbers being off. Just recalculated everything, so they should be all fixed now.

**Comment by kostasx** [comment]
Great!
